name: PicasaWebAlbumDisplay
description: A sample Polymer application
dependencies:
  http: any
  json_object: any
  polymer: any
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: web/picasawebalbumdisplay.html
