name: PicasaWebAlbumDisplay
description: A sample Polymer application
dependencies:
  picasawebalbums:
    path: C:\Users\hangs_000\Documents\GitHub\PicasaWebAlbums
  polymer: any
transformers:
- polymer:
    entry_points: web/picasawebalbumdisplay.html
