name: PicasaWebAlbumDisplay
description: A sample Polymer application
dependencies:
  http: any
  json_object: any
  mock: any
  polymer: any
  polymer_ui_elements: any
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: web/picasawebalbumdisplay.html
